### ISSUE TITLE
Spinning the "Happiness" dial doesn't change anything after the first time

### ISSUE THREAD

**Issue by samuelstevens** [samuelstevens/watsong#49]
Title.

**Comment by AnthonyFortuna** [comment]
Is it only the happiness dial

**Comment by samuelstevens** [comment]
Yep. I think it's because the URL that's constructed has `happiness=0.123` and the Flask server is looking for `valence=0.123`. So I think we can just change the JS code to construct the URL differently.

**Comment by Alex7Li** [comment]
Has this been fixed? It seems to work for me

**Comment by pnavk99** [comment]
#54
